import { StyleSheet } from 'react-native';
import { colors, typography, spacing, borderRadius } from '../../theme/tokens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  scrollContent: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.xxl,
  },
  header: {
    marginBottom: spacing.md,
  },
  screenTitle: {
    fontFamily: typography.fontFamily.heading,
    fontSize: 22,
    color: colors.textPrimary,
    lineHeight: 28,
  },
  screenSubtitle: {
    fontFamily: typography.fontFamily.regular,
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 4,
    lineHeight: 18,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    padding: 14,
    marginBottom: 10,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  cardCategory: {
    fontFamily: typography.fontFamily.bold,
    fontSize: 10,
    color: colors.bidGreen,
    letterSpacing: 1.2,
    marginBottom: 2,
  },
  cardTitle: {
    fontFamily: typography.fontFamily.bold,
    fontSize: 17,
    color: colors.textPrimary,
  },
  frequencyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  frequencyLabel: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 13,
    color: colors.textSecondary,
  },
  frequencyValue: {
    fontFamily: typography.fontFamily.monoBold,
    fontSize: 14,
    color: colors.bidGreen,
  },
  sliderContainer: {
    paddingVertical: 6,
    marginBottom: 2,
  },
  sliderHitArea: {
    height: 36,
    justifyContent: 'center',
  },
  track: {
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    position: 'relative',
    justifyContent: 'center',
  },
  filledTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.bidGreen,
  },
  thumb: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.bidGreen,
    marginLeft: -9,
    shadowColor: colors.bidGreen,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 6,
    elevation: 4,
  },
  sliderLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
    marginBottom: 10,
  },
  sliderRangeText: {
    fontFamily: typography.fontFamily.mono,
    fontSize: 11,
    color: colors.textSecondary,
  },
  presetsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
    marginBottom: 10,
  },
  presetPill: {
    flex: 1,
    paddingVertical: 5,
    borderRadius: borderRadius.sm,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
  },
  presetPillActive: {
    backgroundColor: 'rgba(0, 197, 122, 0.18)',
    borderColor: colors.bidGreen,
  },
  presetText: {
    fontFamily: typography.fontFamily.mono,
    fontSize: 11,
    color: colors.textSecondary,
  },
  presetTextActive: {
    color: colors.bidGreen,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    marginVertical: 6,
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  toggleTextColumn: {
    flex: 1,
    paddingRight: 12,
  },
  toggleHint: {
    color: colors.textMuted,
    fontSize: 11,
    marginTop: 2,
    fontFamily: typography.fontFamily.regular,
  },
  toggleLabel: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 13,
    color: colors.textPrimary,
  },
  inputLabel: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: spacing.xs,
  },
  textInput: {
    backgroundColor: 'rgba(10, 14, 23, 0.8)',
    borderRadius: borderRadius.sm,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    fontFamily: typography.fontFamily.mono,
    fontSize: 13,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: 'rgba(0, 197, 122, 0.18)',
    borderWidth: 1,
    borderColor: colors.bidGreen,
    borderRadius: borderRadius.sm,
    paddingVertical: 10,
    alignItems: 'center',
  },
  primaryButtonText: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 13,
    color: colors.bidGreen,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: borderRadius.sm,
    paddingVertical: 10,
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 13,
    color: colors.textSecondary,
  },
  dangerButton: {
    backgroundColor: 'rgba(255, 59, 105, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255, 59, 105, 0.35)',
    borderRadius: borderRadius.sm,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  dangerButtonText: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 13,
    color: colors.askRed,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  statLabel: {
    fontFamily: typography.fontFamily.regular,
    fontSize: 13,
    color: colors.textSecondary,
  },
  statValue: {
    fontFamily: typography.fontFamily.mono,
    fontSize: 13,
    color: colors.textPrimary,
  },
});
